# frozen_string_literal: true

require_relative "lib/jmv/version"

Gem::Specification.new do |spec|
  spec.name          = "jmv"
  spec.version       = JMV::VERSION
  spec.authors       = ["Ashwin Maroli"]
  spec.email         = ["ashmaroli@gmail.com"]
  spec.homepage      = "https://github.com/ashmaroli/jmv"

  spec.summary       = "Simple tool to enable viewing contents of '.jekyll-metadata' file."
  spec.description   = "Jekyll Metadata file Viewer (JMV) is a simple tool to enable viewing " \
                       "contents of the '.jekyll-metadata' file generated by Jekyll."
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| File.basename(f).start_with?(".") }
  spec.bindir        = "exe"
  spec.executables   = ["jmv"]
  spec.require_paths = ["lib"]

  spec.required_ruby_version = ">= 2.5.0"

  spec.add_dependency "webrick", "~> 1.7"
end
